### ISSUE TITLE
How to debug the scenes in VSCode?

### ISSUE THREAD

**Issue by selvavm** [cbos/grafana-scenes-playground#1]
Hi,

Thanks for the contribution. Do you know if I can set breakpoint and debug using VSCode? I tried with below launch.json but the breakpoint is not hitting in `HellowWorld.tsx` when I click on Hello world

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

```

**Comment by cbos** [comment]
Hi @selvavm 
Thanks for reaching out. 
I have no experience with that (yet), but I don't it is working, as VS code cannot launch a new browser. 
Locally that is used to launch the browser and attach the debugger.

But there is another way:

I am more of the 'old school' debugging with the `debugger;` statement and then I use the developer tools to keep an eye on whatever is happening and I do debug my code. 

I made a change to `.config/tsconfig.json` to add sourcemap files.
![image](https://github.com/cbos/grafana-scenes-playground/assets/255404/aeed8d82-8d1f-4550-9fc1-68ae53e1d87c)

Then I placed the `debugger;` statement in one of the source files.
As mentioned in the blog post, you can open the remote url in the browser. 
Then you can open the Developer tools of your browser and do the debugging:
 
That works as well:
![image](https://github.com/cbos/grafana-scenes-playground/assets/255404/be559ded-468e-4126-b461-3a90d5d3e2ab)

**Comment by selvavm** [comment]
Thank you for answering. I am new to javascript ecosystem and this will be handy method to debug. Also, thanks for the repo, It helped me learn Scenes :)

**Comment by cbos** [comment]
I have two other posts in mind which can help you with developing new scenes as well, I only have to find time to write them.

**Comment by selvavm** [comment]
thank you :) Much appreciated,
