### ISSUE TITLE
How to show drop down (select) values based on a SceneQueryRunner?

### ISSUE THREAD

**Issue by selvavm** [cbos/grafana-scenes-playground#2]
Hi,

Can I ask one more doubt about Grafana scenes? 

I wanted to show repeating panels with a drop down per panel to select the field to show. I have followed the demo and I have made a repeating panel and a drop down using 'setHeaderActions`

```
.setHeaderActions(
   <Select options={[{ label: 'Option 1', value: '1' }]} onChange={() => {}} value="1" />
)
```

Now, I am unsure how I can show the options dynamically from DB using SceneQueryRunner. For a start I tried to just display the `getQueryRunnerWithRandomWalkQuery` but it renders undefined. Something like below,

```
const options = getQueryRunnerWithRandomWalkQuery()
options.runQueries()
options.forceRender()
```

Do you know how I can achieve it?

![image](https://github.com/cbos/grafana-scenes-playground/assets/16543422/51c78fc0-1650-4e04-a171-5d2a85c99183)

**Comment by cbos** [comment]
@selvavm 
I have no experience with this.
You can either ask this at https://github.com/grafana/scenes or the Grafana Community Forum https://community.grafana.com/c/plugin-development/30

**Comment by selvavm** [comment]
thanks @cbos and no worries
